### ISSUE TITLE
some more features

### ISSUE THREAD

**Issue by ducpro0211kk** [sudo-do/discord-selfbot-owo-bot#18]
e.g. manually add gems after gems run out instead of time

**Comment by ducpro0211kk** [comment]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\discord-selfbot-owo-bot-adcbb771533d7714db8ebe0f028ce58fd1626944\discord-selfbot-owo-bot-adcbb771533d7714db8ebe0f028ce58fd1626944\selfpy\client.py", line 301, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Admin\Downloads\discord-selfbot-owo-bot-adcbb771533d7714db8ebe0f028ce58fd1626944\discord-selfbot-owo-bot-adcbb771533d7714db8ebe0f028ce58fd1626944\cheat.py", line 828, in on_ready
    await send_message_with_logging(m[0])
  File "C:\Users\Admin\Downloads\discord-selfbot-owo-bot-adcbb771533d7714db8ebe0f028ce58fd1626944\discord-selfbot-owo-bot-adcbb771533d7714db8ebe0f028ce58fd1626944\cheat.py", line 814, in send_message_with_logging
    await DCL.get_channel(settings["channel"]).send(message)
AttributeError: 'NoneType' object has no attribute 'send'


**I don't understand where is it wrong? Can you help me?**

**Comment by sudo-do** [comment]
Did you selected a channel for bot?
