### ISSUE TITLE
I can't open the python file

### ISSUE THREAD

**Issue by Formeis** [sudo-do/discord-selfbot-owo-bot#21]
the main.py file just opens up and in a split second closes it doesn't do anything i alr have the token and channel id in it

**Comment by Formeis** [comment]
Traceback (most recent call last):
  File "C:\Users\558486505\Desktop\New folder\discord-selfbot-owo-bot-2.2\main.py", line 1, in <module>
    import discum_c844aef
  File "C:\Users\558486505\Desktop\New folder\discord-selfbot-owo-bot-2.2\discum_c844aef\__init__.py", line 2, in <module>
    from .discum import Client
  File "C:\Users\558486505\Desktop\New folder\discord-selfbot-owo-bot-2.2\discum_c844aef\discum.py", line 2, in <module>
    from .start.login import Login
  File "C:\Users\558486505\Desktop\New folder\discord-selfbot-owo-bot-2.2\discum_c844aef\start\login.py", line 1, in <module>
    from ..RESTapiwrap import *
  File "C:\Users\558486505\Desktop\New folder\discord-selfbot-owo-bot-2.2\discum_c844aef\RESTapiwrap.py", line 5, in <module>
    from requests.exceptions import ConnectionError
ModuleNotFoundError: No module named 'requests'

**Comment by sudo-do** [comment]
run this on cmd
`py -m pip install requests`

**Comment by Formeis** [comment]
still didn't work

**Comment by Formeis** [comment]
SyntaxError: invalid syntax
>>> client.gateway.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'client' is not defined

**Comment by Formeis** [comment]
tried running it in python

**Comment by talet1** [comment]
same problem here

**Comment by Formeis** [comment]
sad

**Comment by sudo-do** [comment]
Error says you dont have the module simply install the module

Auto module installer avaible in upcoming rewrite update
