### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tue13589** [sudo-do/discord-selfbot-owo-bot#34]
Traceback (most recent call last):
  File "C:\Users\HuyBui\Desktop\discord-selfbot-owo-bot-1.0.9-release\main.py", line 94, in <module>
    client=discum_c844aef.Client(token=bot.token,proxy_host=bot.proxyserver, proxy_port=bot.proxyport, log=False)
  File "C:\Users\HuyBui\Desktop\discord-selfbot-owo-bot-1.0.9-release\discum_c844aef\discum.py", line 83, in __init__
    self.__super_properties = SuperProperties(self.s, buildnum=build_num, log=self.log).getSuperProperties(self.__user_agent, self.locale)
  File "C:\Users\HuyBui\Desktop\discord-selfbot-owo-bot-1.0.9-release\discum_c844aef\start\superproperties.py", line 57, in getSuperProperties
    reqbuildnum = self.requestBuildNumber()
  File "C:\Users\HuyBui\Desktop\discord-selfbot-owo-bot-1.0.9-release\discum_c844aef\start\superproperties.py", line 21, in requestBuildNumber
    discord_login_page_exploration = Wrapper.sendRequest(self.editedS, 'get', "https://discord.com/login", log=False).text #log set to False cause this takes up console space w/o giving meaningful info
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by sudo-do** [comment]
network error
